[package]
name = "git-ai"
version = "0.1.1"
edition = "2024"


[dependencies]
git2 = "0.20.2"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
similar = "2.7.0"
