# Bob
# Wrote
# This
version: "3"
tasks:
  build:
    desc: Build the project in release mode (native Apple Silicon)
    cmds:
      - cargo build --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/release/git-ai-cli
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  # Validates code compilation without producing binaries (faster than build)
  check:
    desc: Check code without building
    cmds:
      - cargo check

  # Runs static analysis to catch common mistakes and improve code quality
  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  # Automatically formats code according to Rust style guidelines
  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  # Verifies that code follows proper formatting without making changes
  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt -- --check

  # Builds and installs the binary to user's local bin directory for system-wide use
  release:local:
    desc: Build release and install to user bin directory
    deps: [build]
    cmds:
      - cp target/release/git-ai ~/.local/bin/git-ai
      - chmod +x ~/.local/bin/git-ai
