version: "3"
tasks:
  build:
    desc: Build the project in release mode (native Apple Silicon)
    cmds:
      - cargo build --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/release/git-ai-cli
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  check:
    desc: Check code without building
    cmds:
      - cargo check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt -- --check

  release:local:
    desc: Build release and install to user bin directory
    deps: [build]
    cmds:
      - cp target/release/git-ai ~/.local/bin/git-ai
      - chmod +x ~/.local/bin/git-ai
