use crate::repos::test_file::ExpectedLineExt;
use crate::repos::test_repo::TestRepo;
use std::fs;

#[test]
fn test_git_clean_removes_deleted_untracked_file_attribution() {
    let target = TestRepo::new();
    fs::write(target.path().join("base.txt"), "base\n").expect("base should be writable");
    target.stage_all_and_commit("Initial commit").unwrap();
    let mut base = target.filename("base.txt");
    base.assert_committed_lines(lines!["base".unattributed_human()]);
    let mut generated = target.filename("generated.txt");
    generated.set_contents_no_stage(lines!["discarded generated bytes".ai()]);

    target.git(&["clean", "-f", "--", "generated.txt"]).unwrap();
    assert!(target.read_file("generated.txt").is_none());
    fs::write(
        target.path().join("generated.txt"),
        "discarded generated bytes\n",
    )
    .unwrap();
    target
        .stage_all_and_commit("Human recreates cleaned file")
        .unwrap();
    let mut generated = target.filename("generated.txt");
    generated.assert_committed_lines(lines!["discarded generated bytes".unattributed_human()]);
}

#[test]
fn test_git_clean_dry_run_preserves_existing_ai_attribution() {
    let target = TestRepo::new();
    fs::write(target.path().join("base.txt"), "base\n").unwrap();
    target.stage_all_and_commit("Initial commit").unwrap();
    let mut base = target.filename("base.txt");
    base.assert_committed_lines(lines!["base".unattributed_human()]);
    let mut generated = target.filename("kept.txt");
    generated.set_contents_no_stage(lines!["kept AI bytes".ai()]);

    target
        .git(&["clean", "--dry-run", "--", "kept.txt"])
        .unwrap();
    assert_eq!(
        target.read_file("kept.txt").as_deref(),
        Some("kept AI bytes")
    );
    target
        .stage_all_and_commit("Commit file kept by dry run")
        .unwrap();
    let mut generated = target.filename("kept.txt");
    generated.assert_committed_lines(lines!["kept AI bytes".ai()]);
}

#[test]
fn test_git_clean_does_not_remove_tracked_modified_file_attribution() {
    let target = TestRepo::new();
    fs::write(target.path().join("tracked.txt"), "base\n").unwrap();
    target.stage_all_and_commit("Initial commit").unwrap();
    let mut tracked = target.filename("tracked.txt");
    tracked.assert_committed_lines(lines!["base".unattributed_human()]);
    let mut tracked = target.filename("tracked.txt");
    tracked.set_contents_no_stage(lines!["tracked AI edit".ai()]);

    target.git(&["clean", "-fd"]).unwrap();
    assert_eq!(
        target.read_file("tracked.txt").as_deref(),
        Some("tracked AI edit")
    );
    target.stage_all_and_commit("Commit tracked edit").unwrap();
    let mut tracked = target.filename("tracked.txt");
    tracked.assert_committed_lines(lines!["tracked AI edit".ai()]);
}

#[test]
fn test_git_clean_fdx_prunes_ai_file_that_became_ignored() {
    let target = TestRepo::new();
    fs::write(target.path().join("base.txt"), "base\n").unwrap();
    target.stage_all_and_commit("Initial commit").unwrap();
    let mut base = target.filename("base.txt");
    base.assert_committed_lines(lines!["base".unattributed_human()]);
    fs::create_dir_all(target.path().join("cache")).unwrap();
    let mut generated = target.filename("cache/generated.txt");
    generated.set_contents_no_stage(lines!["ignored AI bytes".ai()]);

    // Make the already-checkpointed path ignored while carrying its working
    // attribution across the .gitignore-only commit.
    fs::write(target.path().join(".gitignore"), "cache/\n").unwrap();
    target.git_og(&["add", ".gitignore"]).unwrap();
    target
        .git(&["commit", "-m", "Ignore generated cache"])
        .unwrap();
    let mut ignore = target.filename(".gitignore");
    ignore.assert_committed_lines(lines!["cache/".unattributed_human()]);
    target.git(&["clean", "-fdx"]).unwrap();
    assert!(target.read_file("cache/generated.txt").is_none());

    fs::create_dir_all(target.path().join("cache")).unwrap();
    fs::write(
        target.path().join("cache/generated.txt"),
        "ignored AI bytes\n",
    )
    .unwrap();
    target
        .git_og(&["add", "-f", "cache/generated.txt"])
        .unwrap();
    target
        .git(&["commit", "-m", "Human recreates ignored output"])
        .unwrap();
    let mut generated = target.filename("cache/generated.txt");
    generated.assert_committed_lines(lines!["ignored AI bytes".unattributed_human()]);
}

#[test]
fn test_git_clean_fdx_preserves_ai_file_staged_before_command() {
    let target = TestRepo::new();
    fs::write(target.path().join("base.txt"), "base\n").unwrap();
    target.stage_all_and_commit("Initial commit").unwrap();
    let mut base = target.filename("base.txt");
    base.assert_committed_lines(lines!["base".unattributed_human()]);
    let mut staged = target.filename("staged-output.txt");
    staged.set_contents_no_stage(lines!["staged AI bytes".ai()]);
    target.git_og(&["add", "staged-output.txt"]).unwrap();
    fs::write(target.path().join(".gitignore"), "staged-output.txt\n").unwrap();
    target.git_og(&["add", ".gitignore"]).unwrap();

    target.git(&["clean", "-fdx"]).unwrap();
    assert_eq!(
        target.read_file("staged-output.txt").as_deref(),
        Some("staged AI bytes")
    );
    target
        .git(&["commit", "-m", "Commit pre-staged ignored output"])
        .unwrap();

    let mut staged = target.filename("staged-output.txt");
    staged.assert_committed_lines(lines!["staged AI bytes".ai()]);
}

#[test]
fn test_git_clean_from_subdirectory_does_not_prune_same_named_root_path() {
    // Delay pruning until after the removed path is recreated and staged.
    let target = TestRepo::new_with_daemon_env(&[(
        "GIT_AI_TEST_DELAY_SIDE_EFFECT_MS_FOR_COMMAND",
        "clean=750",
    )]);
    fs::write(target.path().join("base.txt"), "base\n").unwrap();
    target.stage_all_and_commit("Initial commit").unwrap();
    let mut base = target.filename("base.txt");
    base.assert_committed_lines(lines!["base".unattributed_human()]);

    fs::create_dir_all(target.path().join("nested")).unwrap();
    let mut root = target.filename("generated.txt");
    root.set_contents_no_stage(lines!["root AI bytes".ai()]);
    let mut nested = target.filename("nested/generated.txt");
    nested.set_contents_no_stage(lines!["nested AI bytes".ai()]);

    target
        .git_from_working_dir(
            &target.path().join("nested"),
            &["clean", "-f", "--", "generated.txt"],
        )
        .unwrap();
    assert_eq!(
        target.read_file("generated.txt").as_deref(),
        Some("root AI bytes")
    );
    assert!(target.read_file("nested/generated.txt").is_none());

    fs::write(
        target.path().join("nested/generated.txt"),
        "nested AI bytes\n",
    )
    .unwrap();
    target
        .stage_all_and_commit("Commit root and recreated nested files")
        .unwrap();
    let mut root = target.filename("generated.txt");
    root.assert_committed_lines(lines!["root AI bytes".ai()]);
    let mut nested = target.filename("nested/generated.txt");
    nested.assert_committed_lines(lines!["nested AI bytes".unattributed_human()]);
}
