name: PR Comment on Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # push:

jobs:
  comment-on-merge:
    name: Comment on Merged PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-ai
        run: |
          curl -sSL https://gitai.run/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Get git-ai stats
        id: git-ai-stats
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          if [ "${{ github.event_name }}" = "push" ]; then
            COMMIT_SHA="${{ github.sha }}"
          else
            COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          fi
          git-ai stats $COMMIT_SHA > git_ai_stats.txt
          echo "stats_output<<EOF" >> $GITHUB_OUTPUT
          cat git_ai_stats.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Comment on merged PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const script = fs.readFileSync('.github/scripts/comment-pr.js', 'utf8');

            // Set environment variables for the script
            process.env.COMMIT_SHA = '${{ steps.git-ai-stats.outputs.commit_sha }}';
            process.env.STATS_OUTPUT = '${{ steps.git-ai-stats.outputs.stats_output }}';
            process.env.EVENT_NAME = '${{ github.event_name }}';

            // Execute the script
            eval(script);
